### ISSUE TITLE
Porażka obrony doktoratu, co dalej?

### ISSUE THREAD

**Issue by dariusz-izak-doktorat** [dariusz-izak-doktorat/Results#1]
Wyników jest dużo,  ale co dalej?

**Comment by dariusz-izak-doktorat** [comment]
Napewno do obrony konieczne jest ukończenie programu prwlr, który ma importować nazwy genów ze strony www, a tego nie robi.

**Comment by dariusz-izak-doktorat** [comment]
Wyników jest dużo. To, że na realizacje projektu doktoranckiego wydano 160 tysięcy złotych, że tysiące godzin poświęcono na tworzenie programu prwlr jest argumentem za nadaniem stopnia doktora. Doktorant się naprawdę wysilał.

**Comment by dariusz-izak-doktorat** [comment]
Okazuje się, że nie jest wymagane, żeby projekt zakończył się sukcesem.

**Comment by szymon-kaczanowski** [comment]
To prawda. Nie jest wymagane, żeby projekt zakończył się sukcesem. Ale z drugiej strony, olbrzymi nakład pracy włożony w uzyskanie wyników i napisanie kodu w Pythonie, budzi olbrzymie uznanie.
